// <auto-generated />
using System;
using IT_Firm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT_Firm.Migrations
{
    [DbContext(typeof(OrganizationContext))]
    partial class OrganizationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT_Firm.Models.Department", b =>
                {
                    b.Property<int?>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("DepartmentID"));

                    b.Property<string>("DepartmentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentLoocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IT_Firm.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("ProjectDeadline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectDuration")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("IT_Firm.Models.Role", b =>
                {
                    b.Property<int?>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RoleID"));

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("RoleID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("StaffId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("IT_Firm.Models.Skill", b =>
                {
                    b.Property<int?>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SkillID"));

                    b.Property<string>("SkillDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<string>("SkillType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("IT_Firm.Models.Staff", b =>
                {
                    b.Property<int?>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("StaffId"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("StaffAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("IT_Firm.Models.StaffSkill", b =>
                {
                    b.Property<int?>("StaffSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("StaffSkillID"));

                    b.Property<int?>("SkillID")
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("StaffSkillName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffSkillID");

                    b.HasIndex("SkillID");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffSkill");
                });

            modelBuilder.Entity("IT_Firm.Models.Project", b =>
                {
                    b.HasOne("IT_Firm.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IT_Firm.Models.Role", b =>
                {
                    b.HasOne("IT_Firm.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");

                    b.HasOne("IT_Firm.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Project");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("IT_Firm.Models.Staff", b =>
                {
                    b.HasOne("IT_Firm.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IT_Firm.Models.StaffSkill", b =>
                {
                    b.HasOne("IT_Firm.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID");

                    b.HasOne("IT_Firm.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Skill");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
